In [2]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import torch.nn.functional as F
import torch.optim as optim
from torch.autograd import Variable, Function

In [9]:
import numpy as np

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        
        self.conv = nn.Conv2d(1,1,kernel_size=(3,3), stride = 1, padding = 1)
        self.conv.weight = torch.nn.Parameter(data = torch.DoubleTensor([[[[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9]]]]), requires_grad =True) #since the input channel and output channel is 1, dimension of filter is (1x1x3x3)
        self.conv.bias = torch.nn.Parameter(data = torch.DoubleTensor([0]), requires_grad=True)
        self.fc = nn.Linear(9,2)
        self.fc.weight = torch.nn.Parameter(data = torch.DoubleTensor([[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]]), requires_grad = True)
        self.fc.bias = torch.nn.Parameter(data=torch.DoubleTensor([0.0]), requires_grad=True)
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax()
    def forward(self, x):
        x = self.conv(x)
#         print("\nThe output of conv is")
#         print(x)
        x = self.relu(x)
        x = torch.reshape(x,(-1,9))
        x = self.fc(x)
#         print("\nThe output of FC is")
#         print(x)
        x = self.relu(x)
        x = self.softmax(x)
        return x
img = torch.from_numpy(np.ones((1,1,3,3))) #or torch.ones((1,1,3,3))
label = torch.LongTensor([0])

net = Net()
# print(net)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(net.parameters(), lr = 0.001, momentum = 0.9)

for i in range(100):
    output = net(img)
    print(output)
    
    loss = criterion(output, label)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print("\n Loss:")
    print(loss)
    if(i==0 or i == 99):

        print("\n FC gradients :")
        print(net.fc.weight.grad)

        print("\nConv Gradients :")
        print(net.conv.weight.grad)
        print("\nUpdated Conv Weights :")
        print(net.conv.weight)

        print("\nUpdated FC Weights :")
        print(net.fc.weight)
    

tensor([[0.5000, 0.5000]], dtype=torch.float64, grad_fn=<SoftmaxBackward>)

 Loss:
tensor(0.6931, dtype=torch.float64, grad_fn=<NllLossBackward>)

 FC gradients :
tensor([[-0.7000, -0.9750, -0.6000, -0.8250, -1.1250, -0.6750, -0.4000, -0.5250,
         -0.3000],
        [ 0.7000,  0.9750,  0.6000,  0.8250,  1.1250,  0.6750,  0.4000,  0.5250,
          0.3000]], dtype=torch.float64)

Conv Gradients :
tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]], dtype=torch.float64)

Updated Conv Weights :
Parameter containing:
tensor([[[[0.1000, 0.2000, 0.3000],
          [0.4000, 0.5000, 0.6000],
          [0.7000, 0.8000, 0.9000]]]],
       dtype=torch.float64, requires_grad=True)

Updated FC Weights :
Parameter containing:
tensor([[0.1007, 0.2010, 0.3006, 0.4008, 0.5011, 0.6007, 0.7004, 0.8005, 0.9003],
        [0.0993, 0.1990, 0.2994, 0.3992, 0.4989, 0.5993, 0.6996, 0.7995, 0.8997]],
       dtype=torch.float64, requires_grad=True)
tensor([[0.5095, 0.4905]], dtype=torch.

/home/harsh/.local/lib/python3.5/site-packages/ipykernel_launcher.py:25: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
